[package]
org = "ballerina"
name = "java.jms"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["jms"]
repository = "https://github.com/ballerina-platform/module-ballerina-java.jms"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.6.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "java.jms-native"
version = "@toml.version@"
path = "../native/build/libs/java.jms-native-@project.version@.jar"

[[platform.java11.dependency]]
groupId = "javax.jms"
artifactId = "javax.jms-api"
version = "@javax.jms.version@"
path = "./lib/javax.jms-api-@javax.jms.version@.jar"
