[package]
org = "ballerina"
name = "java.jms"
version = "0.0.1"
authors = ["Ballerina"]
keywords = ["jms"]
repository = "https://github.com/ballerina-platform/module-ballerina-java.jms"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.6.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "java.jms-native"
version = "0.0.1"
path = "../native/build/libs/java.jms-native-0.0.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-api"
version = "2.0.7"
path = "./lib/slf4j-api-2.0.7.jar"

[[platform.java11.dependency]]
groupId = "javax.jms"
artifactId = "javax.jms-api"
version = "2.0.1"
path = "./lib/javax.jms-api-2.0.1.jar"
