[package]
org = "ballerinax"
name = "java.jms"
version = "0.1.3"
authors = ["Ballerina"]
keywords = ["jms"]
repository = "https://github.com/ballerina-platform/module-ballerina-java.jms"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.6.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "java.jms-native"
version = "0.1.3"
path = "../native/build/libs/java.jms-native-0.1.3-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-api"
version = "2.0.7"
path = "./lib/slf4j-api-2.0.7.jar"

[[platform.java11.dependency]]
groupId = "javax.jms"
artifactId = "javax.jms-api"
version = "2.0.1"
path = "./lib/javax.jms-api-2.0.1.jar"


[[platform.java11.dependency]]
path = "./lib/activemq-client-5.18.2.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/geronimo-j2ee-management_1.1_spec-1.0.1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/hawtbuf-1.11.jar"
scope = "testOnly"
